-- Flyway V1 Baseline
-- 현재 RDS 스키마 기준 (2026.08.19)
-- pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- users
CREATE TABLE users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP(6) NOT NULL,
    email        VARCHAR(50)  NOT NULL,
    level        VARCHAR(20)  NOT NULL,
    nickname     VARCHAR(30)  NOT NULL,
    password     VARCHAR(255) NOT NULL,
    region       VARCHAR(20),
    total_points INTEGER      NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL,
    vegan_level  VARCHAR(20),
    CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
    CONSTRAINT users_vegan_level_check CHECK (vegan_level IN (
        'FLEXITARIAN','POLLO_PESCO','PESCO','POLLO',
        'LACTO_OVO','LACTO','OVO','VEGAN','FRUITARIAN'
    ))
);

-- challenges
CREATE TABLE challenges (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP(6) NOT NULL,
    current_day   INTEGER      NOT NULL,
    duration_days INTEGER      NOT NULL,
    ended_at      TIMESTAMP(6),
    purpose       VARCHAR(100),
    started_at    TIMESTAMP(6) NOT NULL,
    status        VARCHAR(20)  NOT NULL,
    type          VARCHAR(30)  NOT NULL,
    user_id       BIGINT,
    CONSTRAINT fkle3q0kbl0hsc262e7qnjw6dgw FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT challenges_type_check CHECK (type IN (
        'FLEXITARIAN','POLLO_PESCO','PESCO','POLLO',
        'LACTO_OVO','LACTO','OVO','VEGAN','FRUITARIAN'
    ))
);

-- point_history
CREATE TABLE point_history (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6)  NOT NULL,
    points     INTEGER       NOT NULL,
    reason     VARCHAR(255)  NOT NULL,
    user_id    BIGINT,
    CONSTRAINT fklmm2nu7f5elblp2o2w2rrcwhl FOREIGN KEY (user_id) REFERENCES users(id)
);

-- ingredients
CREATE TABLE ingredients (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calcium      NUMERIC(10,2),
    calories     NUMERIC(10,2),
    carbs        NUMERIC(10,2),
    category     VARCHAR(255),
    co2_per_100g NUMERIC(10,4),
    created_at   TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    fat          NUMERIC(10,2),
    fiber        NUMERIC(10,2),
    iron         NUMERIC(10,2),
    name         VARCHAR(255) NOT NULL,
    name_en      VARCHAR(255),
    omega3       NUMERIC(10,4),
    protein      NUMERIC(10,2),
    source       VARCHAR(255),
    vitamin_b12  NUMERIC(10,4),
    vitamin_d    NUMERIC(10,4)
);

-- meals
CREATE TABLE meals (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ai_feedback          TEXT,
    created_at           TIMESTAMP(6)  NOT NULL,
    image_url            TEXT          NOT NULL,
    ingredients          JSONB,
    is_vegan_compliant   BOOLEAN,
    nutrition            JSONB,
    status               VARCHAR(255)  NOT NULL,
    total_carbon         NUMERIC(10,3),
    vegan_violations     JSONB,
    challenge_id         BIGINT,
    user_id              BIGINT        NOT NULL,
    confirmed_violations JSONB,
    suspected_violations JSONB,
    CONSTRAINT fk247efbp0jo4e3mo0in3pikjvh FOREIGN KEY (challenge_id) REFERENCES challenges(id),
    CONSTRAINT fk677c66qpjr7234luomahc1ale FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT meals_status_check CHECK (status IN ('ANALYZING','DONE','FAILED'))
);

-- carbon_daily
CREATE TABLE carbon_daily (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carbon_date  DATE,
    created_at   TIMESTAMP(6) NOT NULL,
    meal_count   INTEGER,
    total_carbon NUMERIC(10,4),
    user_id      BIGINT       NOT NULL,
    CONSTRAINT fktc0sjc0sadjt7kqm6kg93seh FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uk8agxn348ktqbw32cmmnqakq0u UNIQUE (user_id, carbon_date)
);

-- community_posts
CREATE TABLE community_posts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_count INTEGER,
    content       TEXT         NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL,
    image_url     TEXT         NOT NULL,
    ingredients   JSONB        NOT NULL,
    like_count    INTEGER,
    steps         JSONB        NOT NULL,
    title         VARCHAR(255) NOT NULL,
    updated_at    TIMESTAMP(6) NOT NULL,
    version       BIGINT       NOT NULL,
    user_id       BIGINT       NOT NULL,
    CONSTRAINT fk44o0kkmkldhul00k2lm08bqje FOREIGN KEY (user_id) REFERENCES users(id)
);

-- post_likes
CREATE TABLE post_likes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    post_id    BIGINT       NOT NULL,
    user_id    BIGINT       NOT NULL,
    CONSTRAINT fkhl7eauuj5a85e8jumxyc0l8rh FOREIGN KEY (post_id) REFERENCES community_posts(id),
    CONSTRAINT fkkgau5n0nlewg6o9lr4yibqgxj FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uk5l2rj28vw5oj6f7ox746grokg UNIQUE (post_id, user_id)
);

-- comments
CREATE TABLE comments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content    TEXT         NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    post_id    BIGINT       NOT NULL,
    user_id    BIGINT       NOT NULL,
    CONSTRAINT fk8omq0tc18jd43bu5tjh6jvraq FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fkbre5xli116921c3as7fm0jqo0 FOREIGN KEY (post_id) REFERENCES community_posts(id)
);

-- recipes
CREATE TABLE recipes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content    TEXT         NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    s3_url     VARCHAR(255),
    title      VARCHAR(255) NOT NULL,
    post_id    BIGINT,
    embedding  vector(512),
    image_url  TEXT,
    CONSTRAINT fkgrfgagf0nshn92nd99xdxi0ws FOREIGN KEY (post_id) REFERENCES community_posts(id)
);

-- products
CREATE TABLE products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category    VARCHAR(255),
    created_at  TIMESTAMP(6) NOT NULL,
    description TEXT,
    image_url   VARCHAR(255),
    name        VARCHAR(255) NOT NULL,
    price       NUMERIC(10,2) NOT NULL,
    stock       INTEGER       NOT NULL
);

-- carts
CREATE TABLE carts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    user_id    BIGINT       NOT NULL,
    CONSTRAINT fkb5o626f86h46m4s7ms6ginnop FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uk64t7ox312pqal3p7fg9o503c2 UNIQUE (user_id)
);

-- cart_items
CREATE TABLE cart_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    quantity   INTEGER      NOT NULL,
    cart_id    BIGINT       NOT NULL,
    product_id BIGINT       NOT NULL,
    CONSTRAINT fk1re40cjegsfvw58xrkdp6bac6 FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fkpcttvuq4mxppo8sxggjtn5i2c FOREIGN KEY (cart_id) REFERENCES carts(id),
    CONSTRAINT uk6oue0maw421roerltnxn16a38 UNIQUE (cart_id, product_id)
);

-- orders
CREATE TABLE orders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address         VARCHAR(255),
    address_detail  VARCHAR(255),
    created_at      TIMESTAMP(6)  NOT NULL,
    memo            VARCHAR(255),
    recipient_name  VARCHAR(255),
    recipient_phone VARCHAR(255),
    status          VARCHAR(255)  NOT NULL,
    total_amount    NUMERIC(10,2) NOT NULL,
    user_id         BIGINT        NOT NULL,
    CONSTRAINT fk32ql8ubntj5uh44ph9659tiih FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT orders_status_check CHECK (status IN (
        'PENDING','PAID','SHIPPED','DELIVERED','CANCELLED'
    ))
);

-- order_items
CREATE TABLE order_items (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     TIMESTAMP(6)  NOT NULL,
    price_at_order NUMERIC(38,2) NOT NULL,
    quantity       INTEGER       NOT NULL,
    order_id       BIGINT        NOT NULL,
    product_id     BIGINT        NOT NULL,
    CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fkocimc7dtr037rh4ls4l95nlfi FOREIGN KEY (product_id) REFERENCES products(id)
);
